### ISSUE TITLE
Fix alignment of icons and titles

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-net#8]
![image](https://user-images.githubusercontent.com/28673/92848269-0d3f3680-f3b8-11ea-89d9-0b86dfe780b7.png)

The icons are a little too low for the text.

**Comment by helfi92** [comment]
Alignments of icons is done in https://github.com/taskcluster/taskcluster-net/commit/6cbaa2087cad736f1e3b4a0b55d1130fd26f0ee1.
